## parameters that must be changed for each different run
projectid: 2023020_EVD68_NS
inputpath: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/2023020_EVD68_NS/Input_Data/

## configurable parameters
codepath: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqRepoTempSkyline/PathSeq/Code/
outputpath: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqRepoTempSkyline/PathSeq/

## paths of necessary installs and references on system
bowtieERCCIndex: /data/vrc_his/douek_lab/reference_sets/ERCC/ERCC92
bowtieUnmaskedGenomeIndex: /data/vrc_his/douek_lab/reference_sets/hg19/unmasked/genome
bowtiePrimatePaths: /data/vrc_his/douek_lab/reference_sets/NCBI_nt/20210302/primates
picard: /data/vrc_his/douek_lab/projects/PathSeq/programs/picard/2.18.14/picard.jar
program_PathSeqRemoveHostForKaiju: /data/vrc_his/douek_lab/projects/PathSeq/programs/PathSeqRemoveHostForKaiju/dist/PathSeqRemoveHostForKaiju.jar
PathSeqKaijuConcensusSplitter2_program: /data/vrc_his/douek_lab/projects/PathSeq/programs/PathSeqKaijuConcensusSplitter2/dist/PathSeqKaijuConcensusSplitter2.jar
PathSeqMergeQIIME2TaxAndSalmon_program: /data/vrc_his/douek_lab/projects/PathSeq/programs/PathSeqMergeQIIME2TaxAndSalmon/dist/PathSeqMergeQIIME2TaxAndSalmon.jar
PathSeqSplitOutputTableByTaxonomy_program: /data/vrc_his/douek_lab/projects/PathSeq/programs/PathSeqSplitOutputTableByTaxonomy/dist/PathSeqSplitOutputTableByTaxonomy.jar
blastDB_Mammalia: /data/vrc_his/douek_lab/reference_sets/NCBI_nt/20210716/Mammalia.fa
kaiju_nodes: /data/vrc_his/douek_lab/reference_sets/NCBI_nt/20220512/kaiju/nodes.dmp
kaiju_fmi: /data/vrc_his/douek_lab/reference_sets/NCBI_nt/20220512/kaiju/nr_euk/kaiju_db_nr_euk.fmi
NCBI_nt_kaiju_ref_taxonomy: /data/vrc_his/douek_lab/reference_sets/NCBI_nt/20220512/kaiju/nr_euk/qiime2_formatted_taxonomy.tab
hg38_starDB: /data/vrc_his/douek_lab/reference_sets/hg38/Sequence/STAR/