configfile: "config.yaml"

wildcard_constraints:
    filename = ".+"  # Use 'filename' to represent the entire filename

with open(os.path.join(config["inputpath"], "file_list"), "r") as file:
    FULLSAMPLES = [line.strip().split(".")[0] for line in file]


SAMPLES = [sample.split("_R1_")[0] for sample in FULLSAMPLES]

leftEnding = "_R1_" + FULLSAMPLES[0].split("_R1_")[1]
rightEnding = leftEnding.replace("R1", "R2")

numContigFilterThreads=8

# print("sample name, left ending, right ending, respectively: ")
# print(SAMPLES[0])
# print(leftEnding)
# print(rightEnding)

rule all:
    input:
        expand(os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_filtered",
                    "nonHost_trinity_Origin_" + config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta"),
                    sample=SAMPLES)

# Basic rule for testing environment. Should take all input files,
# and print them each to a file of the same base name.
rule testRuleAll:
    input:
        expand(os.path.join(config["outputpath"], "{sample}.txt"), sample=FULLSAMPLES)

rule testRuleHelper:
    params:
        "this file corresponds to {sample}"
    output:
        os.path.join(config["outputpath"], "{sample}.txt")
    shell:
        """
        echo {params} > {output}
       """

# run bowtie unmasked on samples
rule bowtieUnmasked:
    input:
        scriptPath=os.path.join(config["codepath"], "bowtieUnmaskedGenome.sh"),
        leftReadFile=os.path.join(config["inputpath"], "{sample}" + leftEnding +".fastq.gz"),
        rightReadFile=os.path.join(config["inputpath"], "{sample}" + rightEnding +".fastq.gz"),
        picard=config["program_picard"]
    params:
        outPath=config["outputpath"],
        codePath=config["codepath"],
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        bowtieERCCIndex=config["bowtieERCCIndex"],
        bowtieUnmaskedGenomeIndex=config["bowtieUnmaskedGenomeIndex"]
    output:
        ## following outputs are directly used by subsequent steps:
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/unalignedRead1AgainstGenome_{sample}" + leftEnding + ".fq"),
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/unalignedRead2AgainstGenome_{sample}" + rightEnding + ".fq"),
        ## following outputs are solely informational:
        # first bowtie alignment:
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "ERCC_alignment_rates/ERCC_alignment_rate_{sample}"+ leftEnding +".txt"),
        # second bowtie alignment:
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding, 
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/picard_stderr_{sample}"+ leftEnding +".txt"),
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/picard_stdout_{sample}"+ leftEnding +".txt"),
        # post-processing
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding, "finished_bowtieUnmaskedGenome.txt")
    shell:
        """
        module load java
        which java
        module load bowtie2
        which bowtie2
        module load samtools
        which samtools
        module load R
        which R

        bash {input.scriptPath} {params.codePath} {params.sampleNameLeft} {params.sampleNameRight} {input.leftReadFile} \
        {input.rightReadFile} {params.outPath} {params.bowtieERCCIndex} \
        {params.bowtieUnmaskedGenomeIndex} {input.picard}
        """

rule starAfterBowtie:
    input:
        scriptPath=os.path.join(config["codepath"], "starAfterBowtie.sh"),
        leftUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/unalignedRead1AgainstGenome_{sample}" + leftEnding + ".fq"),
        rightUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_2nd_Bowtie_Alignment_Unmasked_Genome/unalignedRead2AgainstGenome_{sample}" + rightEnding + ".fq"),
    params:
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        codePath=config["codepath"],
        outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding + "/"),
        hgStarDb=config["hg38_starDB"]
    output:
        ## following outputs are directly used by subsequent steps
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_Star_Alignment/{sample}" + leftEnding + "_unalignedRead1AgainstTranscriptome.fq"),
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_Star_Alignment/{sample}" + rightEnding + "_unalignedRead2AgainstTranscriptome.fq"),
        ## following outputs are solely informational
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_Star_Alignment/{sample}" + leftEnding + "_star_alignment_stats.txt")
    shell:
        """
        module load STAR
        which STAR
        module load samtools
        which samtools

        bash {input.scriptPath} {params.codePath} {input.leftUnaligned} {input.rightUnaligned} \
        {params.sampleNameLeft} {params.sampleNameRight} {params.outPath} {params.hgStarDb}
        """

rule bowtiePrimate:
    input:
        scriptPath=os.path.join(config["codepath"], "bowtiePrimate.sh"),
        leftUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_Star_Alignment/{sample}" + leftEnding + "_unalignedRead1AgainstTranscriptome.fq"),
        rightUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "Generated_Data_Star_Alignment/{sample}" + rightEnding + "_unalignedRead2AgainstTranscriptome.fq"),
    params:
        outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding),
        codePath=config["codepath"],
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        primateIndex=config["bowtiePrimatePaths"]
    output:
        ## following outputs are directly used by subsequent steps
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "primate_alignment_rates/unalignedRead1AgainstPrimate_{sample}" + leftEnding + ".fq"),
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "primate_alignment_rates/unalignedRead1AgainstPrimate_{sample}" + rightEnding + ".fq")
        ## following outputs are solely informational
    shell:
        """
        module load bowtie2
        which bowtie2
        module load samtools
        which samtools

        bash {input.scriptPath} {input.leftUnaligned} {input.rightUnaligned} {params.outPath} \
        {params.codePath} {params.sampleNameLeft} {params.sampleNameRight} {params.primateIndex}
        """

## assembly remaining unaligned reads into contigs
rule trinity:
    input:
        scriptPath=os.path.join(config["codepath"], "all_trinity.sh"),
        leftUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "primate_alignment_rates/unalignedRead1AgainstPrimate_{sample}" + leftEnding + ".fq"),
        rightUnaligned=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    "primate_alignment_rates/unalignedRead1AgainstPrimate_{sample}" + rightEnding + ".fq")
    params:
        outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding),
        codePath=config["codepath"],
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        origin=config["origin"],
        minContigLen=config["minContigLen"],
        numThreads="1",
        maxMemory="175G",
        fastp=config["program_fastp"],
        scratchDir=config["scratchDir"]
    output:
        ## following outputs are directly used by subsequent steps
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_output",
                    "formatted_myTrinity_Origin_" + config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta"),
        ## following outputs are solely informational
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_output",
                    "trinity_out_" + str(config["minContigLen"]) + "_Sample_{sample}" + leftEnding + ".txt"),
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_output",
                    "trinity_err_" + str(config["minContigLen"]) + "_Sample_{sample}" + leftEnding + ".txt"),
        # following outputs are intermediate outputs
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_output",
                    "myTrinity_Origin_"+ config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta")
    shell: ## does this really need py-setuptools? what even is that
        """
        module load trinity/2.13.2
        which Trinity
        module load fastp
        which fastp
        module load fastxtoolkit
        which fasta_formatter

        bash {input.scriptPath} {params.codePath} {input.leftUnaligned} {input.rightUnaligned} {params.sampleNameLeft} \
        {params.sampleNameRight} {params.origin} {params.minContigLen} {params.numThreads} \
        {params.maxMemory} {params.outPath} {params.scratchDir}
        """

## blast trinity assembled contigs for further host contamination
rule filterHostBlast:
    input:
        scriptPath=os.path.join(config["codepath"], "array_filter_host.sh"),
        contigs=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                            config["origin"] + "_trinity_output",
                            "formatted_myTrinity_Origin_" + config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta"),
        program_RemoveHostForKaiju=config["program_RemoveHostForKaiju"],
        blastDB_Mammalia=config["blastDB_Mammalia"]
    params:
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding, config["origin"] + "_trinity_filtered"),
        codePath=config["codepath"],
        origin=config["origin"]
    output:
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                    config["origin"] + "_trinity_filtered",
                    "nonHost_trinity_Origin_" + config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta")
    shell:
        """
        bash {input.scriptPath} {params.codePath} {input.contigs} {params.outPath} {params.origin} \
        {input.program_RemoveHostForKaiju} {input.blastDB_Mammalia}
        """

## comment describing rule
rule kaiju:
    input:
        scriptPath=os.path.join(config["codepath"], "protein_kaiju.sh"),
        kaiju_nodes=config["kaiju_nodes"],
        kaiju_fmi=config["kaiju_fmi"],
        nonHostContigs=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
                                    config["origin"] + "_trinity_filtered",
                                    "nonHost_trinity_Origin_" + config["origin"] + "_Sample_{sample}" + leftEnding + ".Trinity.fasta")
    params:
        sampleNameLeft="{sample}" + leftEnding,
        sampleNameRight="{sample}" + rightEnding,
        outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding),
        codePath=config["codepath"],
        origin=config["origin"],
        program_prodigal=config["program_prodigal"],
        program_kaiju=config["program_kaiju"]
    output:
        os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding, config["origin"] + "kaiju_output",
                    "sorted_protein_kaiju_"+ config["origin"] + "_Sample_" + "{sample}" + leftEnding + ".tab")
    shell:
        """
        bash {input.scriptPath} {params.sampleNameLeft} {params.sampleNameRight} {input.nonHostContigs} \
        {params.origin} {params.program_prodigal} {params.program_kaiju} {input.kaiju_nodes} {input.kaiju_fmi} \
        {params.codePath} {params.outPath}
        """

# ## TODO: This should probably be refactored in some way, so its not one script calling 4 scripts
# # rule parseKaijuDoSalmon:
# rule parseKaiju:
#     input:
#         scriptPath=os.path.join(config["codepath"], "parse_protein_kaiju_build_salmon.sh")
#     params:
#         sampleNameLeft="{sample}" + leftEnding,
#         sampleNameRight="{sample}" + rightEnding,
#         outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding),
#         codePath=config["codepath"]
#     output:
        
#     shell:

# rule palmscan
# rule palmScan:
#     input:
#         scriptPath=os.path.join(config["codepath"], "palm_scan.sh")
#         unclassifiedSeqs=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
#                                         config["origin"] + "_salmon_quant",
#                                         "unclassified_sequences.fa")
#     params:
#         program_palmscan=config["program_palmscan"],
#         scratchDir=config["scratchDir"],
#         salmonDataDir=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
#                                     "RNA_salmon_quant"),
#         origin=config["origin"],
#         outPath=os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding),
#         codePath=config["codepath"],
#         scratchDir=config["scratchDir"]
#     output:
#         os.path.join(config["outputpath"], "Sample_{sample}" + leftEnding,
#                     "palmscan",
#                     config["origin"] + "Sample_{sample}" + leftEnding + "_palmscan.fa")
#     shell:
#         """
#         bash {input.scriptPath} {params.program_palmscan} {params.scratchDir} {params.salmonDataDir} \
#         {input.unclassifiedSeqs} {params.origin} {params.outPath} {params.codePath} {params.scratchDir}
#         """