#!/bin/bash
rm bowtieUnmaskedGenome.o*
rm bowtieUnmaskedGenome.e*
rm bowtieUnmaskedGenome.po*
rm bowtieUnmaskedGenome.pe*
rm starAfterBowtie.o*
rm starAfterBowtie.e*
rm PathSeqSubmitter.o*
rm PathSeqSubmitter.e*
rm bowtiePrimate.o*
rm bowtiePrimate.e*
rm bowtiePrimate.po*
rm bowtiePrimate.pe*
rm all_trinity.o*
rm all_trinity.po*
rm all_trinity.e*
rm all_trinity.pe*
rm start_filter_host_kaiju.o*
#rm start_filter_host_kaiju.po*
rm start_filter_host_kaiju.e*
#rm start_filter_host_kaiju.pe*
rm array_filter_host.o*
rm array_filter_host.po*
rm array_filter_host.e*
rm array_filter_host.pe*
rm protein_kaiju.e*
rm protein_kaiju.o*
rm protein_kaiju.po*
rm protein_kaiju.pe*
rm concat_kaiju_build_salmon.e*
rm concat_kaiju_build_salmon.o*
rm concat_kaiju_build_salmon.pe*
rm concat_kaiju_build_salmon.po*
rm salmonQuantSingleLevel.e*
rm salmonQuantSingleLevel.o*
rm salmonQuantSingleLevel.pe*
rm salmonQuantSingleLevel.po*
rm mergeTaxonomyAndQuantificationSingleLevel.o*
rm mergeTaxonomyAndQuantificationSingleLevel.e*
rm mergeTaxonomyAndQuantificationSingleLevel.po*
rm mergeTaxonomyAndQuantificationSingleLevel.pe*
rm prepForDiversity.o*
rm prepForDiversity.e*
rm prepForDiversity.po*
rm prepForDiversity.pe*
rm palm_scan.o*
rm palm_scan.e*
rm palm_scan.pe*
rm palm_scan.po*

