## cluster settings
cluster: sbatch
jobs: 32

## parameters that must be changed for each different run
inputlist: /data/home/parkercol/PathSeq/Tests/Skyline_Full_Test_00/TestInput/file_list
inputdir: /data/home/parkercol/PathSeq/Tests/Skyline_Full_Test_00/TestInput/
origin: RNA
minContigLen: 300

## configurable parameters
codepath: /data/home/parkercol/PathSeq/SlurmBaseCode/
outputpath: /data/home/parkercol/PathSeq/Tests/Skyline_Full_Test_00/Output/
scratchDir: /data/scratch/

## paths of necessary installs and references on system
bowtieERCCIndex: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/ERCC92/ERCC92
bowtieUnmaskedGenomeIndex: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/bowtieHg19Unmasked_2021_Ref/genome
hg38_starDB: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/StarReindex/
bowtiePrimatePaths: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/bowtie_NCBIntPrimate_2021_Ref/primates
blastDB_Mammalia: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/blast_Mammalia_2021_DB/Mammalia.fa
kaiju_nodes: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/kaiju_NCBInt_2022_Ref/nodes.dmp
kaiju_fmi: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/kaiju_NCBInt_2022_Ref/nr_euk/kaiju_db_nr_euk.fmi
NCBI_nt_kaiju_ref_taxonomy: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqReferenceData/kaiju_NCBInt_2022_Ref/nr_euk/qiime2_formatted_taxonomy.tab

## external programs
program_picard: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/picard_2.18.14/picard.jar
program_RemoveHostForKaiju: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/PathSeqRemoveHostForKaiju/dist/PathSeqRemoveHostForKaiju.jar
program_PathSeqKaijuConcensusSplitter2: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/PathSeqKaijuConcensusSplitter2/dist/PathSeqKaijuConcensusSplitter2.jar
program_PathSeqMergeQIIME2TaxAndSalmon: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/PathSeqMergeQIIME2TaxAndSalmon/dist/PathSeqMergeQIIME2TaxAndSalmon.jar
program_PathSeqSplitOutputTableByTaxonomy: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/PathSeqSplitOutputTableByTaxonomy/dist/PathSeqSplitOutputTableByTaxonomy.jar
program_prodigal: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/prodigal/bin
program_kaiju: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/kaiju-v1.9.0-linux-x86_64-static
program_fastp: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/fastp/
program_palmscan: /data/vrc_his/douek_lab/projects/PathSeq/cokie_pathseq_rewrite/PathseqExternalPrograms/palmscan-main/bin/

## resource allocation
rule_resources:
  bowtieUnmasked:
    runtime: 2880
    mem_mb: 65536
  starAfterBowtie:
    runtime: 2880
    mem_mb: 65536
  bowtiePrimate:
    runtime: 2880
    mem_mb: 65536
  trinity:
    runtime: 21600
    mem_mb: 32768
  filterHostBlast:
    runtime: 4320
    mem_mb: 131072
  kaiju:
    runtime: 2880
    mem_mb: 524288
  buildSalmon:
    runtime: 2880
    mem_mb: 131072
  salmonQuant:
    runtime: 2880
    mem_mb: 131072
  mergeTaxAndQuant:
    runtime: 2880
    mem_mb: 131072